language: node_js
node_js:
    - "8"
    - "10"
    - "12"

services:
    - redis-server

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install --no-save nyc codecov
    - npm run cover
    - npx codecov

sudo: false
